build:
    tsc

run-d1:
    < input.txt just run
run-d2:
    just run

run:
    node main.js

example:
    just build
    < p1in.txt just run

debug:
    just build
    DEBUG=1 < p1in.txt just run

trace:
    just build
    TRACE=1 < p1in.txt just run
